### PR TITLE
Added Token Removal on Start

### PR DESCRIPTION
**Pull request by Gurrman375**
I had issues revolving around authentication so I decided to delete the token.json everytime the program runs.
image
image
Current issue is program fails to shut down after MCC shuts Down:
image
It will shut down but fails to run the extra commands.
I need to modify one of the break lines.
Now Xbox is available.
image

### CODE REVIEW

**Comment by kay-el-zed** [comment]
I've noticed that the token stored in token.json will occasionally become invalid after some time. Not sure on the exact timing but I've noticed it happen after a couple weeks if not using it. Is your token failing sooner than that? 

Only reason I ask is because re-entering credentials every time the app is launched isn't a great experience. My token still works just fine after I ran `xbox-authenticate` about 2 weeks ago. I'd prefer it so that `removetoken.removeExisting()` be called when `authenticate.main()` hits an `AuthenticationException`, and not during every single run.

Aside from that, I like the prompt for removing tokens on exit.

**Comment by Gurrman375** [comment]
Alright I'll modify that. I did notice that the tokens don't last forever and that entering your username and password is very inconvenient.

**Comment by kay-el-zed** [comment]
Appreciate the changes. Also loving the Xbox addition. I'll go ahead and merge.

**Comment by Gurrman375** [comment]
Do that once I fix everything

**Comment by kay-el-zed** [comment]
Alright, just let me know when to merge.

**Comment by Gurrman375** [comment]
Nevermind. I found the issue.

**Comment by Gurrman375** [comment]
Ready to merge

**Pull request merged**
