### PR TITLE
Python and JS Interactions

### PR DESCRIPTION
**Pull request by Gurrman375**
Due to xbox-webapi not giving me the data I wanted I was searching for the past year for a module to use. This past month I came up on these two modules provided by https://github.com/XboxReplay/ and got to work.

Right now it will always prompt password, but I'm working on that atm. Just pushing this change so that no one thinks I'm dead and people can actually use the RPC client.

Package to test here: https://github.com/Gurrman375/HaloMCC-DiscordRPC/releases/tag/0.3.0

### CODE REVIEW

**Comment by Gurrman375** [comment]
Now I have more improved UI. Subprocess' are the only issue for this UI.
image
image
image

**Comment by Gurrman375** [comment]
Hey kay-el-zed can you please review the pull request.

**Comment by kay-el-zed** [comment]
Apologies for the delay. I'll admit I'm a bit amazed at how far you've taken the project - I never expected it to get this big. Merged.

**Comment by Gurrman375** [comment]
It took forever to even find a library to authenticate and use easily.
Steam inviting was easy to figure out but I need to work out xbox and window store.

Also can you also include a new release on your page?

**Pull request merged**
